package pirelli

//list any import classes here.
import model.PLCEvent;
import model.RiskyEvent;
import function utils.RestFunctions.*;
import function utils.ProcFunctions.*;

// declaration 
declare window RiskWindow 
	RiskyEvent () over window:time( 40s )
end

// rules

rule "Risky Event"
no-loop 

	when
		$plcEvent: PLCEvent( input2 > 10.0 )
	then
		insert(new RiskyEvent($plcEvent));
				
end

rule "Risky Situation"
    when 
		accumulate ( RiskyEvent() from window RiskWindow ;
       		$c : count();
       		$c >= 3 )
       	$lastEvent : RiskyEvent() over window:length(1)

    then
//    	restPost("Alert " + $lastEvent);
//    	startProcess($lastEvent.getId());
    	System.out.println("ok "+ $lastEvent );

end
