package pirelli

//list any import classes here.
import model.PLCEvent;
import function utils.RestFunctions.*;

// declaration 
declare window RiskWindow 
	PLCEvent( input2 > 10.0 ) over window:time( 40s )
end

// rules

rule "PLC Rule"
no-loop 

    when 
		accumulate ( PLCEvent() from window RiskWindow ;
       		$c : count();
       		$c >= 3 )
       	$lastEvent : PLCEvent() over window:length(1)
       	PLCEvent( this == $lastEvent ) from window RiskWindow ;

    then
    	restPost("Alert " + $lastEvent);
    	//System.out.println("ok "+ $lastEvent );

end
